from project_trello.main import format_text

def test_format_text():
    raw_data = [{'id': '5fb488b973e82701afd6e8be',
  'checkItemStates': None,
  'closed': False,
  'dateLastActivity': '2021-03-03T01:54:05.077Z',
  'desc': '[Web APIs, Part 10: Final Project](https://github.com/alissa-huskey/python-class/blob/master/docs/lessons/web-apis.md#part-10-final-project)',
  'descData': None,
  'dueReminder': -1,
  'idBoard': '5f6173c879c2a140a3cc7abc',
  'idList': '5f6173c879c2a140a3cc7abe',
  'idMembersVoted': [],
  'idShort': 23,
  'idAttachmentCover': None,
  'idLabels': ['5f6173c879c2a140a3cc7adb'],
  'manualCoverAttachment': False,
  'name': 'Trello CLI Project',
  'pos': 557055,
  'shortLink': 'VTIIqfX7',
  'isTemplate': False,
  'cardRole': None,
  'badges': {'attachmentsByType': {'trello': {'board': 0, 'card': 2}},
   'location': False,
   'votes': 0,
   'viewingMemberVoted': False,
   'subscribed': True,
   'fogbugz': '',
   'checkItems': 0,
   'checkItemsChecked': 0,
   'checkItemsEarliestDue': None,
   'comments': 0,
   'attachments': 2,
   'description': True,
   'due': None,
   'dueComplete': False,
   'start': None},
  'dueComplete': False,
  'due': None,
  'idChecklists': [],
  'idMembers': ['5d9289a18511323659821144'],
  'labels': [{'id': '5f6173c879c2a140a3cc7adb',
    'idBoard': '5f6173c879c2a140a3cc7abc',
    'name': 'Projects',
    'color': 'purple'}],
  'shortUrl': 'https://trello.com/c/VTIIqfX7',
  'start': None,
  'subscribed': True,
  'url': 'https://trello.com/c/VTIIqfX7/23-trello-cli-project',
  'cover': {'idAttachment': None,
   'color': None,
   'idUploadedBackground': None,
   'size': 'normal',
   'brightness': 'light',
   'idPlugin': None}},
 {'id': '5f6173c879c2a140a3cc7ad5',
  'checkItemStates': None,
  'closed': False,
  'dateLastActivity': '2021-03-03T01:54:07.467Z',
  'desc': '',
  'descData': None,
  'dueReminder': 1440,
  'idBoard': '5f6173c879c2a140a3cc7abc',
  'idList': '5f6173c879c2a140a3cc7abe',
  'idMembersVoted': [],
  'idShort': 4,
  'idAttachmentCover': None,
  'idLabels': ['5f6173c879c2a140a3cc7adb'],
  'manualCoverAttachment': False,
  'name': 'Write a rock/paper/scissors game',
  'pos': 622591,
  'shortLink': 'ZXxnseRj',
  'isTemplate': False,
  'cardRole': None,
  'badges': {'attachmentsByType': {'trello': {'board': 0, 'card': 0}},
   'location': False,
   'votes': 0,
   'viewingMemberVoted': False,
   'subscribed': False,
   'fogbugz': '',
   'checkItems': 0,
   'checkItemsChecked': 0,
   'checkItemsEarliestDue': None,
   'comments': 0,
   'attachments': 0,
   'description': False,
   'due': '2020-09-23T04:07:00.000Z',
   'dueComplete': False,
   'start': None},
  'dueComplete': False,
  'due': '2020-09-23T04:07:00.000Z',
  'idChecklists': [],
  'idMembers': [],
  'labels': [{'id': '5f6173c879c2a140a3cc7adb',
    'idBoard': '5f6173c879c2a140a3cc7abc',
    'name': 'Projects',
    'color': 'purple'}],
  'shortUrl': 'https://trello.com/c/ZXxnseRj',
  'start': None,
  'subscribed': False,
  'url': 'https://trello.com/c/ZXxnseRj/4-write-a-rock-paper-scissors-game',
  'cover': {'idAttachment': None,
   'color': None,
   'idUploadedBackground': None,
   'size': 'normal',
   'brightness': 'light',
   'idPlugin': None}}]
    
    text = """Name: Trello CLI Project
Url: https://trello.com/c/VTIIqfX7
Due Date:

Projects
Name: Write a rock/paper/scissors game
Url: https://trello.com/c/ZXxnseRj
Due Date:2020-09-23T04:07:00.000Z
Projects
Jimmy Woo rulez"""
    assert format_text(raw_data) == text


